### ISSUE TITLE
Vsf to odoo api requests giving error

### ISSUE THREAD

**Issue by creativefurniture** [cristian-g/vsf-odoo#31]
Hello,
I am trying to install vsf-odoo. I installed and i see the module on odoo. 
From vsf i entered localhost:8069 and all routes to api seems to work. 
Issue is all api requests turned with 500 internal server error on odoo side. 

`web_1  | 2019-10-27 09:13:32,879 1 INFO odoo werkzeug: 172.23.0.1 - - [27/Oct/2019 09:13:32] "GET /api/catalog/vue_storefront_catalog/product/_search?_source_exclude=description%2Csgn%2C%2A.sgn%2Cmsrp_display_actual_price_type%2C%2A.msrp_display_actual_price_type%2Crequired_options&_source_include=type_id%2Csku%2Cname%2Ctax_class_id%2Cspecial_price%2Cspecial_to_date%2Cspecial_from_date%2Cprice%2CpriceInclTax%2CoriginalPriceInclTax%2CoriginalPrice%2CspecialPriceInclTax%2Cid%2Cimage%2Csale%2Cnew%2Cconfigurable_children.image%2Cconfigurable_children.sku%2Cconfigurable_children.price%2Cconfigurable_children.special_price%2Cconfigurable_children.priceInclTax%2Cconfigurable_children.specialPriceInclTax%2Cconfigurable_children.originalPrice%2Cconfigurable_children.originalPriceInclTax%2Cconfigurable_children.color%2Cconfigurable_children.size%2Cconfigurable_children.id%2Cconfigurable_children.tier_prices%2Cproduct_links%2Curl_path%2Curl_key%2Cstatus%2Ctier_prices&from=0&size=50&sort=updated_at%3Adesc HTTP/1.1" 500 - 1 0.000 0.003
web_1  | 2019-10-27 09:13:32,883 1 ERROR odoo werkzeug: Error on request:
web_1  | Traceback (most recent call last):
web_1  |   File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 205, in run_wsgi
web_1  |     execute(self.server.app)
web_1  |   File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 193, in execute
web_1  |     application_iter = app(environ, start_response)
web_1  |   File "/usr/lib/python3/dist-packages/odoo/service/server.py", line 409, in app
web_1  |     return self.app(e, s)
web_1  |   File "/usr/lib/python3/dist-packages/odoo/service/wsgi_server.py", line 128, in application
web_1  |     return application_unproxied(environ, start_response)
web_1  |   File "/usr/lib/python3/dist-packages/odoo/service/wsgi_server.py", line 117, in application_unproxied
web_1  |     result = odoo.http.root(environ, start_response)
web_1  |   File "/usr/lib/python3/dist-packages/odoo/http.py", line 1320, in __call__
web_1  |     return self.dispatch(environ, start_response)
web_1  |   File "/usr/lib/python3/dist-packages/odoo/http.py", line 1293, in __call__
web_1  |     return self.app(environ, start_wrapped)
web_1  |   File "/usr/lib/python3/dist-packages/werkzeug/wsgi.py", line 599, in __call__
web_1  |     return self.app(environ, start_response)
web_1  |   File "/usr/lib/python3/dist-packages/odoo/http.py", line 1488, in dispatch
web_1  |     result = ir_http._dispatch()
web_1  |   File "/usr/lib/python3/dist-packages/odoo/addons/website_sale/models/ir_http.py", line 15, in _dispatch
web_1  |     return super(IrHttp, cls)._dispatch()
web_1  |   File "/usr/lib/python3/dist-packages/odoo/addons/auth_signup/models/ir_http.py", line 19, in _dispatch
web_1  |     return super(Http, cls)._dispatch()
web_1  |   File "/usr/lib/python3/dist-packages/odoo/addons/web_editor/models/ir_http.py", line 22, in _dispatch
web_1  |     return super(IrHttp, cls)._dispatch()
web_1  |   File "/usr/lib/python3/dist-packages/odoo/addons/http_routing/models/ir_http.py", line 397, in _dispatch
web_1  |     result = super(IrHttp, cls)._dispatch()
web_1  |   File "/usr/lib/python3/dist-packages/odoo/addons/utm/models/ir_http.py", line 26, in _dispatch
web_1  |     response = super(IrHttp, cls)._dispatch()
web_1  |   File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_http.py", line 207, in _dispatch
web_1  |     return cls._handle_exception(e)
web_1  |   File "/usr/lib/python3/dist-packages/odoo/addons/website/models/ir_http.py", line 195, in _handle_exception
web_1  |     return super(Http, cls)._handle_exception(exception)
web_1  |   File "/usr/lib/python3/dist-packages/odoo/addons/utm/models/ir_http.py", line 31, in _handle_exception
web_1  |     response = super(IrHttp, cls)._handle_exception(exc)
web_1  |   File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_http.py", line 177, in _handle_exception
web_1  |     return request._handle_exception(exception)
web_1  |   File "/usr/lib/python3/dist-packages/odoo/http.py", line 776, in _handle_exception
web_1  |     return super(HttpRequest, self)._handle_exception(exception)
web_1  |   File "/usr/lib/python3/dist-packages/odoo/http.py", line 314, in _handle_exception
web_1  |     raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
web_1  |   File "/usr/lib/python3/dist-packages/odoo/tools/pycompat.py", line 87, in reraise
web_1  |     raise value
web_1  |   File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_http.py", line 203, in _dispatch
web_1  |     result = request.dispatch()
web_1  |   File "/usr/lib/python3/dist-packages/odoo/http.py", line 835, in dispatch
web_1  |     r = self._call_function(**self.params)
web_1  |   File "/usr/lib/python3/dist-packages/odoo/http.py", line 346, in _call_function
web_1  |     return checked_call(self.db, *args, **kwargs)
web_1  |   File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 97, in wrapper
web_1  |     return f(dbname, *args, **kwargs)
web_1  |   File "/usr/lib/python3/dist-packages/odoo/http.py", line 339, in checked_call
web_1  |     result = self.endpoint(*a, **kw)
web_1  |   File "/usr/lib/python3/dist-packages/odoo/http.py", line 941, in __call__
web_1  |     return self.method(*args, **kw)
web_1  |   File "/usr/lib/python3/dist-packages/odoo/http.py", line 519, in response_wrap
web_1  |     response = f(*args, **kw)
web_1  |   File "/var/lib/odoo/.local/share/Odoo/addons/12.0/vue_storefront/controllers/public.py", line 26, in products
web_1  |     applied_filters = json.loads(payload.get('request')).get('_appliedFilters')
web_1  |   File "/usr/lib/python3.5/json/__init__.py", line 312, in loads
web_1  |     s.__class__.__name__))
web_1  | TypeError: the JSON object must be str, not 'NoneType' - - -
`
and i tried : http://localhost:8069/api/user/refresh
`ended with {
    "message": "missing access token in request header",
    "type": "access_token_not_found"
}`

I think i am doing something wrong but i am not sure can you please help me?

**Comment by ladrua** [comment]
I am having same issue, did you ever figure it out @creativefurniture ?
